export const locations = {
  Беларусь: ['Минск', 'Брест', 'Гомель', 'Гродно', 'Витебск', 'Могилев'],
  Россия: [
    'Москва',
    'Санкт-Петербург',
    'Новосибирск',
    'Екатеринбург ',
    'Казань',
    'Нижний Новгород',
    'Челябинск',
    'Красноярск',
    'Самара',
    'Уфа',
    'Ростов-на-Дону',
    'Омск',
    'Краснодар',
    'Воронеж',
    'Волгоград',
    'Пермь',
  ],
  'The United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'San Antonio', 'San Diego'],
  Poland: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin'],
};
